server:
  port: 8080
  http2:
    enabled: true
  #spring.datasource.url=jdbc:mysql://${MYSQL_SERVICE}:3306/${MYSQL_DATABASE}
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_SERVICE:localhost}:3306/${MYSQL_DATABASE:test_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:aA1@9876}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:changelog/master.yaml
management:
  endpoints:
    web:
      exposure:
        include: "*"

email-service:
  url: http://localhost:8086

oauth2:
  google:
    client-id: 25433810652-k1p0s8if0e521ofcq5g5cn73mf6qpj56.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8080/api/v1/oauth2/callback
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    access-token-url: https://oauth2.googleapis.com/token
    user-info-url: https://openidconnect.googleapis.com/v1/userinfo

