spring:
  application:
    name: demo
  profiles:
    active: local

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.jdbc.datasource: INFO
    com.zaxxer.hikari: INFO  # For HikariCP
